- hosts: replica
  tasks:
    - name: Install PostgreSQL
      apt:
        name: "postgresql-{{ pg_version }}"
        update_cache: yes

    - name: Setup replication configuration
      lineinfile:
        path: /etc/postgresql/{{ pg_version }}/main/postgresql.conf
        line: "primary_conninfo = 'host={{ groups['primary'][0] }} port=5432 user=replica_user password=replica_password'"
